package edu.project2;

public enum RenderIcons {
    VERTEX,
    HOR_EDGE,
    VERT_PART_EDGE,
    HOR_HOLLOW,
    VERT_HOLLOW,
    HOR_GATE,
    HOR_GATE_WALKED,
    VERT_TRANSITION,
    PATH_SEGMENT_VERT,
    PATH_SEGMENT_HOR_FROM_WEST,
    PATH_SEGMENT_HOR_FROM_EAST,
    PATH_SEGMENT_HOR_FULL,
    PATH_HOR_VISITED,
    FROM_EAST_VISITED,
    FROM_WEST_VISITED,
    HOR_TRANSITION,
    VISITED,
    DEAD_END
}
